[package]
name = "mecha_character"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev ="testnet" }
# suins = { git = "https://github.com/mystenlabs/suins-contracts/", subdir = "packages/suins", rev = "releases/testnet/core/v2" }
utils = { git = "https://github.com/mystenlabs/suins-contracts/", subdir = "packages/utils", rev = "releases/testnet/core/v2" }


[addresses]
sui = "0x2"
utils = "0x6ed81fd808a23eae2da488052334d50478b36527474fc99707c1aed0e43104b1"
mecha_character="0x0"
